project:
  type: website
  output-dir: _site

website:
  title: "Anderson | ML Portfolio"
  search: true # Activa el motor de búsqueda global integrado
  # Barra de navegación con tu paleta de colores integrada
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Inicio"
      - href: about.qmd
        text: "Sobre Mí & Educación"
      - text: "Proyectos de Ciencia de Datos"
        menu:
          - text: "📩 Detección de Spam (NLP)"
            href: proyectos/proyecto_spam/index.qmd
          - text: "🖼️ Clasificación de Imágenes (CNN)"
            href: proyectos/proyecto_imagenes/index.qmd
  comments:
    giscus:
      repo: "Andersoncrs/prueba_quarto"
      repo-id: "R_kgDOTAk6bg"
      category: "General"
      category-id: "DIC_kwDOTAk6bs4C_kpo"

execute:
  freeze: true # Activa la caché global para evitar compilar 50 proyectos simultáneos

format:
  html:
    theme: [cosmo, styles.scss] # Aplica la base 'cosmo' pero la sobrescribe con tu CSS/SASS
    toc: true
    code-copy: true